### ISSUE TITLE
What do you mean? Our team is concerned now

### ISSUE THREAD

**Issue by tieorange** [Salat-Cx65/AdvancedBiometricPromptCompat#105]
https://github.com/Salat-Cx65/AdvancedBiometricPromptCompat/blob/fa9036476aa6e6ef626fbc1d47f8b9a76b379eba/biometric/src/main/java/dev/skomlach/biometric/compat/utils/hardware/Android28Hardware.kt#L268

**Comment by Salat-Cx65** [comment]
It's a bit outdated comment, but still can be valid - I'll check ASAP.
On 'pure' API28 implementation (built-in BiometricPrompt API)  is no way to get 'isBiometricEnrolled' results for specific biometric, like Iris/Face, etc.
So, some tricks have used that try to determine by indirect signs which biometric data are used (like "if NOT fingerprint BUT something enabled in the System Settings").
There are edge cases where we cannot tell exactly what type of biometrics is registered - for example, if it is Samsung with Face and Iris - in which case the code can give a false-positive result. It can happen if you set BiometricApi.BIOMETRICPROMPT + BiometricType.FACE or BiometricApi.BIOMETRICPROMPT + BiometricType.IRIS

Fortunately, for Samsung with Face and Iris, the 'legacy' check should work correctly, so for general cases when you use BiometricApi.AUTO/LEGACY + BiometricType.FACE/IRIS all should work fine.

**Comment by Salat-Cx65** [comment]
I made few changes in the library, also add the new section to the README
https://github.com/Salat-Cx65/AdvancedBiometricPromptCompat#false-positive-andor-false-negative-detection

**Comment by tieorange** [comment]
Thanks mate!
